language: c
sudo: false

compiler:
  - gcc

script:
  - gcc main.c -o test.exe

deploy:
  provider: releases
  api_key: $TESTAUTOMATEDRELEASE_GITHUB
  file_glob: true
  file: bin/Release/test.exe
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
